//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionsApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuctionsApp.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found an active auction for this car..
        /// </summary>
        public static string ErrorActiveAuctionForCarNotFound {
            get {
                return ResourceManager.GetString("ErrorActiveAuctionForCarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction is active..
        /// </summary>
        public static string ErrorAuctionIsActive {
            get {
                return ResourceManager.GetString("ErrorAuctionIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction is not active..
        /// </summary>
        public static string ErrorAuctionIsNotActive {
            get {
                return ResourceManager.GetString("ErrorAuctionIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid amount is equal or lower than the highest bid amount..
        /// </summary>
        public static string ErrorBidAmountLowerThanHighestAmount {
            get {
                return ResourceManager.GetString("ErrorBidAmountLowerThanHighestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car is already in active auction..
        /// </summary>
        public static string ErrorCarInActiveAuction {
            get {
                return ResourceManager.GetString("ErrorCarInActiveAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car not found in inventory..
        /// </summary>
        public static string ErrorCarNotFound {
            get {
                return ResourceManager.GetString("ErrorCarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car not found in inventory or is already in active auction..
        /// </summary>
        public static string ErrorCarNotFoundOrInActiveAuction {
            get {
                return ResourceManager.GetString("ErrorCarNotFoundOrInActiveAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Id already exists..
        /// </summary>
        public static string ErrorDuplicatedCarId {
            get {
                return ResourceManager.GetString("ErrorDuplicatedCarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search criteria..
        /// </summary>
        public static string ErrorInvalidSearchCriteria {
            get {
                return ResourceManager.GetString("ErrorInvalidSearchCriteria", resourceCulture);
            }
        }
    }
}
